<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-D9B72J2S" failures="1" tests="2" name="com.crm.qa.testcases.LoginPageTest" time="75.311" errors="0" timestamp="2022-08-09T15:38:08 IST" skipped="0">
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="VerifyLoginPageTitleTest" time="39.342">
    <failure message="expected [Cogmento RM] but found [Cogmento CRM]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Cogmento RM] but found [Cogmento CRM]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.crm.qa.testcases.LoginPageTest.VerifyLoginPageTitleTest(LoginPageTest.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- VerifyLoginPageTitleTest -->
  <system-out/>
  <testcase classname="com.crm.qa.testcases.LoginPageTest" name="VerifyLoginTest" time="35.969"/>
  <system-out/>
</testsuite> <!-- com.crm.qa.testcases.LoginPageTest -->
